### ISSUE TITLE
why this issue?

### ISSUE THREAD

**Issue by CWQFT** [ld199609/BCM-DTI#1]
![image](https://github.com/ld199609/BCM-DTI/assets/109148773/e275a939-105d-4f83-8fe3-858c4fe6c5c4)

I have a problem as this:

Traceback (most recent call last):
  File "SSCNN_train.py", line 281, in <module>
    write2txt("../data/test_result" + "_split_random_" + dataset_name, test_result)
  File "/home/user1/data/zwh/BCM-DTI-master/utils/file_helper.py", line 91, in write2txt
    with open(file_name+".txt","a+") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/test_result_split_random_DAVIS.txt'

I don't know why. Can you help me? Thanks!!

**Comment by 1026Zzh** [comment]
> ![image](https://user-images.githubusercontent.com/109148773/264910918-e275a939-105d-4f83-8fe3-858c4fe6c5c4.png)
> 
> I have a problem as this:
> 
> Traceback (most recent call last): File "SSCNN_train.py", line 281, in write2txt("../data/test_result" + "_split_random_" + dataset_name, test_result) File "/home/user1/data/zwh/BCM-DTI-master/utils/file_helper.py", line 91, in write2txt with open(file_name+".txt","a+") as f: FileNotFoundError: [Errno 2] No such file or directory: '../data/test_result_split_random_DAVIS.txt'
> 
> I don't know why. Can you help me? Thanks!!

I also have such confusion, in addition, the source code for DTI_dataset_config() seems to be missing, if you know, can you

**Comment by hwxia** [comment]
I have a problem as this:

Traceback (most recent call last):
  File "/home/hwxia/BCM-DTI-master/SSCNN_train.py", line 243, in <module>
    words2idx_d, words2idx_p = load_train_val_test_set(input_path, decompose,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hwxia/BCM-DTI-master/SSCNN_utils.py", line 257, in load_train_val_test_set
    np.save(input_path+"smiles",trainSmiles+valSmiles+testSmiles)
  File "<__array_function__ internals>", line 200, in save
  File "/opt/anaconda3/lib/python3.11/site-packages/numpy/lib/npyio.py", line 521, in save
    arr = np.asanyarray(arr)
          ^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10473,) + inhomogeneous part.

I don't know why. Can you help me? Thanks!!!!!
